events { }

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    autoindex off;

    map $request_method $cors_method {
        OPTIONS 1;
        default 0;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            return 404;
        }

        location /files/G:/ {
            alias /mnt/g/;
            expires 7d;
            add_header Cache-Control "public";
            add_header Access-Control-Allow-Origin '*' always;
            add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS' always;
            add_header Access-Control-Allow-Headers '*' always;
            if ($cors_method) {
                return 204;
            }
        }

        location /files/D:/ {
            alias /mnt/d/;
            expires 7d;
            add_header Cache-Control "public";
            add_header Access-Control-Allow-Origin '*' always;
            add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS' always;
            add_header Access-Control-Allow-Headers '*' always;
            if ($cors_method) {
                return 204;
            }
        }

        location /files/E:/ {
            alias /mnt/e/;
            expires 7d;
            add_header Cache-Control "public";
            add_header Access-Control-Allow-Origin '*' always;
            add_header Access-Control-Allow-Methods 'GET, HEAD, OPTIONS' always;
            add_header Access-Control-Allow-Headers '*' always;
            if ($cors_method) {
                return 204;
            }
        }
    }
}

