spring:
  application:
    name: catalog-service
  datasource:
    url: ${CATALOG_DATASOURCE_URL:jdbc:postgresql://localhost:18110/catalog_db}
    username: ${CATALOG_DATASOURCE_USERNAME:catalog_user}
    password: ${CATALOG_DATASOURCE_PASSWORD:change-me-catalog}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

server:
  port: ${CATALOG_SERVER_PORT:18101}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
